server:
  port: 8900

spring:
  config:
    import:
      - app/cors/cors.yml
      - app/time/time.yml

  application:
    name: aop-demo

  profiles:
    active: prod

  mvc:
    converters:
      preferred-json-mapper: gson

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db.url:jdbc:mysql://localhost:3306/aop?allowPublicKeyRetrieval=true}
    username: ${db.username:root}
    password: ${db.password:root}
    hikari:
      connection-timeout: 100_000
      idle-timeout: 600_000
      maximum-pool-size: 300
      minimum-idle: 5
      max-lifetime: 10_000
      leak-detection-threshold: 2_000

  jpa:
    database: mysql
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
    hibernate:
      ddl-auto: none

  data:
    redis:
      host: localhost
      port: 6379
